### ISSUE TITLE
Definir diagrama de casos de uso

### ISSUE THREAD

**Issue by nullbeam** [nullbeam/turismo-dias-core#1]

**Comment by AstridBH** [comment]
Diagrama de casos de uso:
https://lucid.app/lucidchart/60793bb1-0f53-4b4e-8b5f-35cf5a039397/edit?viewport_loc=-380%2C40%2C2180%2C1110%2C.Q4MUjXso07N&invitationId=inv_50b54b28-7315-4269-a9c3-5c677ff166fa
