### ISSUE TITLE
Definir diagrama de componentes

### ISSUE THREAD

**Issue by nullbeam** [nullbeam/turismo-dias-core#2]

**Comment by PieroPq** [comment]
https://lucid.app/lucidchart/a2b464b3-3a61-408e-813c-a0f1e7f0cf41/edit?viewport_loc=-1203%2C-171%2C2993%2C1516%2C.Q4MUjXso07N&invitationId=inv_8c38d1e5-ea64-4103-ad6e-53723e4b4452
