### ISSUE TITLE
Definir propuesta de valor y triple impacto

### ISSUE THREAD

**Issue by nullbeam** [nullbeam/turismo-dias-core#4]
Enlaces referenciales

- https://www.linkedin.com/pulse/mis-herramientas-propuesta-de-valor-triple-impacto-luis-madrid/?originalSubdomain=es
- https://creately.com/diagram/example/j7iqpxf31/new-uber-value-proposition-canvas-classic
- https://www.academia.edu/32964200/PLAN_EMPRENDEDOR_DE_TRIPLE_IMPACTO

**Comment by cgozu** [comment]
Triple impacto: 

Impacto Social: La aplicación para Turismo Dias tiene un impacto social al mejorar la accesibilidad, comodidad y experiencia de los usuarios al buscar, reservar y pagar viajes, ofreciendo un servicio más personalizado y fortaleciendo la economía local.

Impacto Económico: La implementación de la aplicación optimiza la gestión de servicios y flotas para Turismo Dias, lo que conlleva una mayor eficiencia en las operaciones y un mejor control de las reservas. Esto resulta en una mejora de la rentabilidad y una reducción de los costos operativos, lo que a su vez beneficia a la empresa y a sus empleados. Además, al facilitar el pago electrónico, la aplicación agiliza el proceso de transacción y reduce la dependencia del efectivo, generando mayor seguridad y comodidad para los clientes y el negocio.

Impacto Ambiental: La aplicación contribuye a la sostenibilidad ambiental al reducir la necesidad de impresión de boletos y otros documentos físicos. Al permitir la consulta de información de servicios a través de la aplicación, se reduce la generación de papel y se fomenta la utilización de medios digitales. Asimismo, la optimización de la gestión de flotas ayuda a reducir las emisiones de gases contaminantes al planificar rutas más eficientes y minimizar los trayectos vacíos.

**Comment by cgozu** [comment]
Propuesta de valor
[cosa.pdf](https://github.com/jmiranda1996/turismo-dias-core/files/11647932/cosa.pdf)
