### ISSUE TITLE
Crear el dataset en csv para alimentar el programa

### ISSUE THREAD

**Issue by nullbeam** [nullbeam/turismo-dias-core#7]
El dataset debe tener por lo menos 500 datos que se ajuste al diagrama de clases

**Comment by nullbeam** [comment]
Aca se puede generar data https://www.mockaroo.com/

**Comment by AndreVMG** [comment]
ADMINISTRADOR: 100 personas
CLIENTE: 400 personas

[DATA_ADMINISTRADOR.csv](https://github.com/jmiranda1996/turismo-dias-core/files/11784064/DATA_ADMINISTRADOR.csv)
[DATA_CLIENTES.csv](https://github.com/jmiranda1996/turismo-dias-core/files/11784065/DATA_CLIENTES.csv)
